# ==============================================================================
# 09_emotional_figures.R
#
# Forest plots for the emotional attention-bias analyses.
#
# This script uses the output generated by:
#   code/07_primary_emotional_analysis.R
#
# Outcomes:
#   - Attention bias score: happy
#   - Attention bias score: anger
#   - Attention bias score: fear
#
# Manuscript:
# Residential Early-Life Air Pollution Exposure and Oculomotor Markers of
# Cognitive Workload in Children: A Prospective Birth Cohort Study
# ==============================================================================


# ==============================================================================
# 1. Required packages
# ==============================================================================

required_packages <- c(
  "openxlsx",
  "dplyr",
  "tibble",
  "stringr",
  "ggplot2",
  "grid"
)

missing_packages <- required_packages[
  !required_packages %in% rownames(installed.packages())
]

if (length(missing_packages) > 0) {
  stop(
    "The following required packages are not installed: ",
    paste(missing_packages, collapse = ", ")
  )
}

invisible(
  lapply(
    required_packages,
    library,
    character.only = TRUE
  )
)


# ==============================================================================
# 2. Paths
# ==============================================================================

results_path <- file.path(
  "results",
  "emotional_attention_bias",
  "07_primary_emotional_analysis.xlsx"
)

plots_dir <- file.path(
  "results",
  "emotional_attention_bias",
  "figures"
)

dir.create(
  plots_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

if (!file.exists(results_path)) {
  stop(
    "Primary emotional-analysis results were not found at: ",
    results_path,
    "\nRun code/07_primary_emotional_analysis.R before this script."
  )
}


# ==============================================================================
# 3. Read primary-analysis results
# ==============================================================================

results <- openxlsx::read.xlsx(
  results_path,
  sheet = "Primary_results"
) |>
  tibble::as_tibble()

required_columns <- c(
  "exposure",
  "outcome",
  "estimate_per_iqr",
  "ci_low_per_iqr",
  "ci_high_per_iqr",
  "p_value",
  "significant_meff"
)

missing_columns <- setdiff(
  required_columns,
  names(results)
)

if (length(missing_columns) > 0) {
  stop(
    "The following required columns are missing from Primary_results: ",
    paste(missing_columns, collapse = ", ")
  )
}


# ==============================================================================
# 4. Labels and ordering
# ==============================================================================

emotional_outcomes <- c(
  "FixTD_biasHappy",
  "FixTD_biasAnger",
  "FixTD_biasFear"
)

outcome_labels <- c(
  FixTD_biasHappy = "Happy",
  FixTD_biasAnger = "Anger",
  FixTD_biasFear  = "Fear"
)

parse_pollutant <- function(exposure) {

  dplyr::case_when(
    stringr::str_starts(exposure, "PM25") ~ "PM2.5",
    stringr::str_starts(exposure, "NO2")  ~ "NO2",
    stringr::str_starts(exposure, "BC")   ~ "BC",
    TRUE                                  ~ NA_character_
  )
}

parse_window <- function(exposure) {

  dplyr::case_when(
    exposure == "BC_urine" ~ "Urinary BC",
    stringr::str_detect(exposure, "trim1$") ~ "Trimester 1",
    stringr::str_detect(exposure, "trim2$") ~ "Trimester 2",
    stringr::str_detect(exposure, "trim3$") ~ "Trimester 3",
    stringr::str_detect(exposure, "whole_preg$") ~ "Whole pregnancy",
    stringr::str_detect(exposure, "first1000days$") ~ "First 1000 days",
    stringr::str_detect(exposure, "Lastw$") ~ "Last week",
    stringr::str_detect(exposure, "Lastm$") ~ "Last month",
    stringr::str_detect(exposure, "last1y$") ~ "Last year",
    TRUE ~ exposure
  )
}

parse_exposure_family <- function(exposure) {

  dplyr::case_when(

    exposure %in% c(
      "BC_trim1", "BC_trim2", "BC_trim3", "BC_whole_preg",
      "PM25_trim1", "PM25_trim2", "PM25_trim3", "PM25_whole_preg",
      "NO2_trim1", "NO2_trim2", "NO2_trim3", "NO2_whole_preg",
      "BC_first1000days", "PM25_first1000days", "NO2_first1000days"
    ) ~ "Early-life exposure",

    exposure %in% c(
      "BC_Lastw", "BC_Lastm", "BC_last1y",
      "PM25_Lastw", "PM25_Lastm", "PM25_last1y",
      "NO2_Lastw", "NO2_Lastm", "NO2_last1y",
      "BC_urine"
    ) ~ "Recent exposure",

    TRUE ~ NA_character_
  )
}


results_plot <- results |>
  dplyr::filter(
    outcome %in% emotional_outcomes
  ) |>
  dplyr::mutate(
    pollutant = parse_pollutant(exposure),
    exposure_window = parse_window(exposure),
    exposure_family = parse_exposure_family(exposure),
    outcome_label = unname(
      outcome_labels[outcome]
    )
  ) |>
  dplyr::filter(
    !is.na(exposure_family),
    !is.na(outcome_label),
    is.finite(estimate_per_iqr),
    is.finite(ci_low_per_iqr),
    is.finite(ci_high_per_iqr)
  )


# ==============================================================================
# 5. Forest-plot function
# ==============================================================================

plot_forest <- function(
    df,
    output_basename,
    exposure_levels,
    show_significance = TRUE
) {

  df <- df |>
    dplyr::mutate(
      exposure_window = factor(
        exposure_window,
        levels = rev(exposure_levels)
      ),
      outcome_label = factor(
        outcome_label,
        levels = c(
          "Happy",
          "Anger",
          "Fear"
        )
      ),
      pollutant = factor(
        pollutant,
        levels = c(
          "BC",
          "NO2",
          "PM2.5"
        )
      )
    )

  # Colors retained from the original manuscript plotting workflow.
  pollutant_colors <- c(
    "BC"    = "#1b9e77",
    "NO2"   = "#d95f02",
    "PM2.5" = "#7570b3"
  )

  p <- ggplot2::ggplot(
    df,
    ggplot2::aes(
      x = estimate_per_iqr,
      y = exposure_window,
      xmin = ci_low_per_iqr,
      xmax = ci_high_per_iqr
    )
  ) +
    ggplot2::geom_vline(
      xintercept = 0,
      linetype = 2,
      linewidth = 0.5
    ) +
    ggplot2::geom_errorbarh(
      ggplot2::aes(
        color = pollutant
      ),
      height = 0,
      linewidth = 0.7
    ) +
    ggplot2::geom_point(
      ggplot2::aes(
        fill = pollutant,
        color = pollutant
      ),
      shape = 21,
      size = 2,
      stroke = 0.4
    ) +
    ggplot2::facet_grid(
      rows = ggplot2::vars(pollutant),
      cols = ggplot2::vars(outcome_label),
      scales = "free_x",
      space = "free_y"
    ) +
    ggplot2::scale_color_manual(
      values = pollutant_colors,
      drop = FALSE,
      name = "Pollutant"
    ) +
    ggplot2::scale_fill_manual(
      values = pollutant_colors,
      drop = FALSE,
      name = "Pollutant"
    ) +
    ggplot2::scale_y_discrete(
      drop = FALSE,
      expand = ggplot2::expansion(
        mult = c(0.12, 0.18)
      )
    ) +
    ggplot2::scale_x_continuous(
      expand = ggplot2::expansion(
        mult = c(0.12, 0.12)
      )
    ) +
    ggplot2::labs(
      x = "Change in attention-bias score per IQR increase in exposure",
      y = NULL
    ) +
    ggplot2::theme_classic(
      base_size = 11
    ) +
    ggplot2::theme(
      strip.placement = "outside",
      strip.text.y.right = ggplot2::element_text(
        angle = 0,
        size = 9
      ),
      strip.text.x = ggplot2::element_text(
        size = 9
      ),
      strip.background = ggplot2::element_blank(),
      panel.spacing.x = grid::unit(
        8,
        "pt"
      ),
      panel.spacing.y = grid::unit(
        14,
        "pt"
      ),
      legend.position = "bottom",
      axis.text.y = ggplot2::element_text(
        size = 8
      ),
      axis.text.x = ggplot2::element_text(
        size = 8
      ),
      plot.title = ggplot2::element_blank(),
      plot.subtitle = ggplot2::element_blank()
    ) +
    ggplot2::coord_cartesian(
      clip = "off"
    )

  if (isTRUE(show_significance)) {

    significant_data <- df |>
      dplyr::filter(
        significant_meff %in% TRUE
      )

    if (nrow(significant_data) > 0) {

      x_range <- range(
        c(
          df$ci_low_per_iqr,
          df$ci_high_per_iqr
        ),
        na.rm = TRUE
      )

      offset <- diff(
        x_range
      ) * 0.025

      if (
        !is.finite(offset) ||
        offset == 0
      ) {
        offset <- 0.01
      }

      significant_data <- significant_data |>
        dplyr::mutate(
          star_x = dplyr::if_else(
            estimate_per_iqr >= 0,
            ci_high_per_iqr + offset,
            ci_low_per_iqr - offset
          )
        )

      p <- p +
        ggplot2::geom_text(
          data = significant_data,
          ggplot2::aes(
            x = star_x,
            label = "*"
          ),
          size = 4
        )
    }
  }

  png_file <- file.path(
    plots_dir,
    paste0(
      output_basename,
      ".png"
    )
  )

  svg_file <- file.path(
    plots_dir,
    paste0(
      output_basename,
      ".svg"
    )
  )

  ggplot2::ggsave(
    filename = png_file,
    plot = p,
    width = 13.5,
    height = 16.9,
    units = "cm",
    dpi = 300
  )

  ggplot2::ggsave(
    filename = svg_file,
    plot = p,
    width = 13.5,
    height = 16.9,
    units = "cm"
  )

  message(
    "Figure written to: ",
    png_file
  )

  message(
    "Figure written to: ",
    svg_file
  )

  invisible(p)
}


# ==============================================================================
# 6. Recent exposure figure
# ==============================================================================

recent_plot_data <- results_plot |>
  dplyr::filter(
    exposure_family ==
      "Recent exposure"
  )

recent_levels <- c(
  "Urinary BC",
  "Last year",
  "Last month",
  "Last week"
)

plot_forest(
  df = recent_plot_data,
  output_basename =
    "emotional_recent_exposure_forest_plot",
  exposure_levels =
    recent_levels,
  show_significance = TRUE
)


# ==============================================================================
# 7. Early-life exposure figure
# ==============================================================================

early_life_plot_data <- results_plot |>
  dplyr::filter(
    exposure_family ==
      "Early-life exposure"
  )

early_life_levels <- c(
  "Trimester 1",
  "Trimester 2",
  "Trimester 3",
  "Whole pregnancy",
  "First 1000 days"
)

plot_forest(
  df = early_life_plot_data,
  output_basename =
    "emotional_early_life_exposure_forest_plot",
  exposure_levels =
    early_life_levels,
  show_significance = TRUE
)

message(
  "Emotional attention-bias forest plots completed."
)
